
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed
 */
public class add extends javax.swing.JFrame {

    String query; 
    ResultSet rset ; 
    Image img ;

   
     
    public add() {
        initComponents();
        
        try{
			UIManager.setLookAndFeel("com.easynth.lookandfeel.EaSynthLookAndFeel")	;
			SwingUtilities.updateComponentTreeUI(this);
			}catch(Exception e){e.printStackTrace();
    }
        
        img = new ImageIcon("exist.png").getImage();
        jLabel8.setIcon(new ImageIcon(img));
        DB.initializeconnection();
         jComboBox1.addItem("");
         jComboBox2.addItem("");
combo2_initialize();
        query = "SELECT name FROM foxproject.product group by name " ; 
        try {
         rset =  DB.stmt.executeQuery(query);
          while (rset.next()) {        
           jComboBox1.addItem(rset.getString(1));
        }
         
        } catch (SQLException ex) {
            Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("أضافه عنصر جديد");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 0, 210, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("أسم الصنف");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(534, 80, 140, 50);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(180, 90, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("النوع");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 150, 70, 40);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(180, 150, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("سعر الجملة");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 230, 150, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField2.setNextFocusableComponent(jTextField3);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(200, 230, 110, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("سعر البيع");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 230, 90, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField1.setNextFocusableComponent(jTextField2);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(420, 230, 110, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("الكمية ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 230, 50, 40);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField3.setNextFocusableComponent(jTextField4);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(40, 230, 80, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("رقم الباركود");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(550, 290, 140, 50);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setNextFocusableComponent(jButton2);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(350, 300, 180, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("إضافة");
        jButton2.setNextFocusableComponent(jButton1);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 370, 80, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("رجوع");
        jButton3.setNextFocusableComponent(jTextField5);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 390, 90, 40);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setNextFocusableComponent(jTextField6);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(340, 90, 160, 30);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setNextFocusableComponent(jTextField1);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(340, 150, 160, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("جديــد");
        jButton1.setNextFocusableComponent(jButton3);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 390, 80, 40);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 300, 60, 40);

        jButton4.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        jButton4.setText("بحث سكانر");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(210, 310, 89, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     MainPage x = new MainPage();
     x.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
             
        jTextField5.setText(jComboBox1.getSelectedItem().toString());
        if(jTextField5.getText().isEmpty()&& jComboBox2.getSelectedItem()!=null)
            combo2_initialize();
        else if(!jTextField5.getText().isEmpty())
        {
            query = "SELECT type FROM foxproject.product where name = '"+jTextField5.getText()+"'" ;
            
            try {
                rset = DB.stmt.executeQuery(query);
                if(jComboBox2.getItemCount()>0)
                                     jComboBox2.removeAllItems();
                    
                
            } catch (SQLException ex) {
                Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
     if(jComboBox2.getSelectedItem() != null)
        if(jComboBox2.getSelectedItem().toString().equals(jTextField6.getText())&&! jTextField6.getText().isEmpty())
        set_barcode();
        else
        {
             jTextField4.setEnabled(true);
              jTextField4.setText("");
             jLabel8.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
        if(jComboBox2.getSelectedItem()!= null)
        jTextField6.setText(jComboBox2.getSelectedItem().toString());
        else 
            jTextField6.setText("");
        try {
            if(rset!= null&&rset.isBeforeFirst())
            {
                jComboBox2.addItem("");
                while (rset.next()) {
                jComboBox2.addItem(rset.getString(1));
            }
        }
        } catch (SQLException ex) {
            Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         if(jComboBox1.getSelectedItem().toString().equals(jTextField5.getText())&&! jTextField5.getText().isEmpty())
        set_barcode();
         else
         {jTextField4.setEnabled(true);
          jTextField4.setText("");
            jLabel8.setVisible(false);
         }  
        
    }//GEN-LAST:event_jComboBox2ActionPerformed
    
    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new add().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try{
        if(!jLabel8.isVisible())
        {
        if(jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty()
               || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty() || jTextField6.getText().isEmpty())
           JOptionPane.showMessageDialog(null,"برجاء اكمال البيانات");
            
        
       else 
        {   query = "SELECT * FROM foxproject.product where barcode = "+jTextField4.getText() ; 
        
            if(DB.stmt.executeQuery(query).next())
            {JOptionPane.showMessageDialog(null,"الباركود مسجل مسبقـا!");
            return;
            }
            else 
            {
            query = "INSERT INTO `foxproject`.`product` (`barcode`, `name`, `type`, `quantity`, `Wholesale_price`, `Selling_price`) "
                    + "VALUES ('"+jTextField4.getText()+"','"+jTextField5.getText()+"','"+jTextField6.getText()+"','"+jTextField3.getText()+"','"
                    +jTextField1.getText()+"','"+jTextField2.getText()+"')";
                
                if(DB.stmt.executeUpdate(query)>0)
                {
                   JOptionPane.showMessageDialog(null, "تم الاضافه بنجاح", "Success", 2, new ImageIcon("Ok.png"));
                
                if(JOptionPane.OK_OPTION==0)
                {
                new add().setVisible(true);
                this.dispose();
                }
                }
            
            }
        
        
      
        }
        
    }                                        
        else {
            if(jTextField3.getText() != null &&!jTextField3.getText().equals(""))
            {   if(jTextField1.getText().equals("")&&jTextField2.getText().equals(""))
            query = "UPDATE `foxproject`.`product` \n" +
"SET quantity = quantity +" + Integer.parseInt(jTextField3.getText())+
" WHERE barcode = '"+jTextField4.getText()+"'" ; 
                else 
                    if(jTextField1.getText().equals("")||jTextField2.getText().equals(""))
                    { JOptionPane.showMessageDialog(null, "برجاء اكمال البيانات");
                    return;
                    }
                    else
                    query = "UPDATE `foxproject`.`product` SET `quantity`= quantity + "
                            +Integer.parseInt(jTextField3.getText())+ ", `Wholesale_price`= "+Double.parseDouble(jTextField1.getText())
                            + ",`Selling_price`="+Double.parseDouble(jTextField2.getText())+"WHERE `barcode`='"+jTextField4.getText()+"'" ; 
            }
            else {
                if(jTextField1.getText().equals("")||jTextField2.getText().equals(""))
                {  JOptionPane.showMessageDialog(null, "برجاء اكمال البيانات");
                return;
                }
                else
                    query = "UPDATE `foxproject`.`product` SET `Wholesale_price`= "+Double.parseDouble(jTextField1.getText())
                            + ",`Selling_price`="+Double.parseDouble(jTextField2.getText())+"WHERE `barcode`='"+jTextField4.getText()+"'" ;
            
            }
            System.out.println("query "+ query);
            
            
           if(DB.stmt.executeUpdate(query)>0)
                JOptionPane.showMessageDialog(null, "تم تحديـث البيانات بنجـاح!", "Success", 2, new ImageIcon("Ok.png"));
            
           else 
                 JOptionPane.showMessageDialog(null, "لم يتم تعديل البيانات!", "error", 2, new ImageIcon("Fail.png"));
            
        }
       }
       catch(Exception ex) {
       
      JOptionPane.showMessageDialog(null, "فشـل!", "Fail", 2, new ImageIcon("Fail.png"));
       
       }    
              
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        jLabel8.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables


void set_barcode(){

query = "SELECT barcode FROM foxproject.product where name = '"+jTextField5.getText()+"' and type = '"+ jTextField6.getText()+"'" ;
   
        try {
            rset = DB.stmt.executeQuery(query);
         if(rset.next())
          {
            jTextField4.setText(rset.getString(1));
            jTextField4.setEnabled(false);
            jLabel8.setVisible(true);
        }
        else
         {
             jTextField4.setEnabled(true);
             jTextField4.setText("");
            jLabel8.setVisible(false);
         }
        
        
        }catch (SQLException ex) {
            Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
        }




}

void combo2_initialize(){

query = "SELECT type FROM foxproject.product group by type " ;
        try {
            rset =  DB.stmt.executeQuery(query);
            while (rset.next()) {        
           jComboBox2.addItem(rset.getString(1));
        }
        } catch (SQLException ex) {
            Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        

}



}
