
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamed
 */
public class Future extends javax.swing.JFrame {

    DB db = new DB() ;
    DefaultTableModel model ;
    ResultSet rset;
    String query;
    
    public Future() {
        initComponents();
        
        
        updateFuturePaidBtn.hide();
        updateFuturePaidLbl.hide();
        updateFuturePaidConfBtn.hide();
        updateFuturePaidTxt.hide();
    }
    
    private void search(JTextField text)
    {
        if(text.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"من فضلك ادخل رقم التليفون");
        }
        
        else
        {
            
        Object[] row = new Object[5] ;
        query = "Select * from client where mob_no = '" + text.getText() + "'" ;
        
        try 
        {
            rset = DB.stmt.executeQuery(query) ;
            if (!rset.next())
            {
                 JOptionPane.showMessageDialog(null, "هذا العميل غير مسجل");
                              
                           
            }
            
            
            else
            {
                do
                {
                  row[4] = rset.getString(2) ;
                  row[3] = rset.getString(3) ;
                  row[2] = rset.getDouble(4) ;
                  row[1] = rset.getDouble(5) ;
                  row[0] =(double) row[2] - (double) row[1] ;
                
                  model = (DefaultTableModel) searchFutureTbl.getModel() ;
                  model.addRow(row) ;
                } while(rset.next());
            }
        }
        
        catch (SQLException ex) 
        {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
      }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchFutureTxt = new javax.swing.JTextField();
        searchFutureCBox = new javax.swing.JComboBox();
        searchFutureLbl = new javax.swing.JLabel();
        searchFutureBtn = new javax.swing.JButton();
        noSearchFutureBtn = new javax.swing.JButton();
        updateFutureBtn = new javax.swing.JButton();
        updateFuturePaidLbl = new javax.swing.JLabel();
        updateFuturePaidConfBtn = new javax.swing.JButton();
        updateFuturePaidTxt = new javax.swing.JTextField();
        updateFuturePaidBtn = new javax.swing.JButton();
        futureMainBtn = new javax.swing.JButton();
        jScrollPaneFuture = new javax.swing.JScrollPane();
        searchFutureTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        searchFutureTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFutureTxtActionPerformed(evt);
            }
        });

        searchFutureCBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchFutureCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "عميل برقم التليفون", "الكل" }));
        searchFutureCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFutureCBoxActionPerformed(evt);
            }
        });

        searchFutureLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchFutureLbl.setText("بحث عن:");

        searchFutureBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchFutureBtn.setText("بحث");
        searchFutureBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchFutureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFutureBtnActionPerformed(evt);
            }
        });

        noSearchFutureBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        noSearchFutureBtn.setText("الغاء");
        noSearchFutureBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noSearchFutureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSearchFutureBtnActionPerformed(evt);
            }
        });

        updateFutureBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateFutureBtn.setText("تحديث");
        updateFutureBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateFutureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFutureBtnActionPerformed(evt);
            }
        });

        updateFuturePaidLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateFuturePaidLbl.setText("المبلغ المدفوع: ");

        updateFuturePaidConfBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateFuturePaidConfBtn.setText("تأكيد");
        updateFuturePaidConfBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateFuturePaidConfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFuturePaidConfBtnActionPerformed(evt);
            }
        });

        updateFuturePaidTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateFuturePaidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFuturePaidTxtActionPerformed(evt);
            }
        });

        updateFuturePaidBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateFuturePaidBtn.setText("دفع");
        updateFuturePaidBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateFuturePaidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFuturePaidBtnActionPerformed(evt);
            }
        });

        futureMainBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        futureMainBtn.setText("القائمة الرئيسية");
        futureMainBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        futureMainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                futureMainBtnActionPerformed(evt);
            }
        });

        searchFutureTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "المتبقى", "المدفوع", "المبلغ الكلى", "رقم الموبايل", "اسم العميل"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchFutureTbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        searchFutureTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFutureTblMouseClicked(evt);
            }
        });
        searchFutureTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFutureTblKeyTyped(evt);
            }
        });
        jScrollPaneFuture.setViewportView(searchFutureTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(noSearchFutureBtn)
                        .addGap(75, 75, 75)
                        .addComponent(searchFutureBtn)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(updateFuturePaidConfBtn)
                                .addGap(37, 37, 37)
                                .addComponent(updateFuturePaidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(updateFuturePaidLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateFuturePaidBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateFutureBtn)
                                .addGap(39, 39, 39)
                                .addComponent(searchFutureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchFutureCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchFutureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))))
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(futureMainBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneFuture)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFutureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchFutureCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchFutureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateFutureBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFutureBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noSearchFutureBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPaneFuture, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateFuturePaidTxt)
                        .addGap(5, 5, 5))
                    .addComponent(updateFuturePaidConfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateFuturePaidBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateFuturePaidLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(futureMainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFutureTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFutureTxtActionPerformed
        searchFutureBtnActionPerformed(evt);
    }//GEN-LAST:event_searchFutureTxtActionPerformed

    private void searchFutureCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFutureCBoxActionPerformed
        searchFutureTxt.setText(null);
        if(searchFutureCBox.getSelectedIndex() == 0)
        {
            searchFutureTxt.setVisible(true);
            updateFutureBtn.setVisible(true);
        }
        else
        {
            searchFutureTxt.setVisible(false);
            updateFutureBtn.setVisible(false);
        }
    }//GEN-LAST:event_searchFutureCBoxActionPerformed

    private void searchFutureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFutureBtnActionPerformed
       if(searchFutureCBox.getSelectedIndex() == 0)
       {
          if (!db.ValueIsExist(searchFutureTbl, 3 , searchFutureTxt.getText()))
          {
              search(searchFutureTxt);
          }
        else
          {
              JOptionPane.showMessageDialog(null, "تم البحث بالفعل");
          }
       }//end if
       
       else if(searchFutureCBox.getSelectedIndex() == 1)
       {
           Object[] row = new Object[5] ;
           query = "Select * from client " ;
           try 
        {
            rset = DB.stmt.executeQuery(query) ;
            if (!rset.next())
            {
                JOptionPane.showMessageDialog(null,"لا يوجد اى عميل");
            }
            else
            {
                do 
                {                    
                    row[4] = rset.getString(2) ;
                    row[3] = rset.getString(3) ;
                    row[2] = rset.getDouble(4) ;
                    row[1] = rset.getDouble(5) ;
                    row[0] =(double) row[2] - (double) row[1] ;
                
                    model = (DefaultTableModel) searchFutureTbl.getModel() ;
                    if (!db.ValueIsExist(searchFutureTbl, 3 , row[3].toString()))
                            {
                                model.addRow(row) ;
                            }
                    
                } while (rset.next());
                
                
                
            }
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(SearchProduct.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
        }
           
       }
       
    }//GEN-LAST:event_searchFutureBtnActionPerformed

    private void noSearchFutureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSearchFutureBtnActionPerformed
        if(searchFutureTbl.getRowCount() == 0)
        {
            JOptionPane.showMessageDialog(null, "تم الالغاء بالفعل");
        }
        else
        {
            searchFutureTxt.setText(null);
            model.setRowCount(0);
            updateFuturePaidBtn.setVisible(false);
            updateFuturePaidLbl.setVisible(false);
            updateFuturePaidConfBtn.setVisible(false);
            updateFuturePaidTxt.setVisible(false);
            JOptionPane.showMessageDialog(null, "تم الالغاء");
        }       
        
    }//GEN-LAST:event_noSearchFutureBtnActionPerformed

    private void updateFutureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFutureBtnActionPerformed
        if (!db.ValueIsExist(searchFutureTbl, 3 , searchFutureTxt.getText()))
        {
            search(searchFutureTxt);
        }
        if(searchFutureTbl.getRowCount() == 0)
        {
            updateFuturePaidBtn.setVisible(false);
        }
        else
        {
            updateFuturePaidBtn.setVisible(true);
        }

    }//GEN-LAST:event_updateFutureBtnActionPerformed

    private void updateFuturePaidConfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFuturePaidConfBtnActionPerformed
       
        try {
               if(Double.parseDouble(updateFuturePaidTxt.getText())>Double.parseDouble(model.getValueAt(model.getRowCount()-1,0).toString())){
               JOptionPane.showMessageDialog(null, "المدفوع اكبر من المتبقي");
               return;
             }
               if(Double.parseDouble(updateFuturePaidTxt.getText()) < 0)
               {
                   JOptionPane.showMessageDialog(new JPanel(), "من فضلك ادخل المبلغ بالموجب", "Error", JOptionPane.ERROR_MESSAGE);
                   updateFuturePaidTxt.setText(null);
                   return;
               }
            String updateQuery = "UPDATE client SET paid = paid + '" + Double.parseDouble(updateFuturePaidTxt.getText()) + "' WHERE mob_no = '" + searchFutureTxt.getText() + "'";
            int rowCount = DB.stmt.executeUpdate(updateQuery);
            if (rowCount == 0) 
            {
                JOptionPane.showMessageDialog(new JPanel(), "خطأ فى تحديث البيانات", "Error", JOptionPane.ERROR_MESSAGE);
                updateFuturePaidTxt.setText(null);
            } 
            else 
            {
                int rowIndex = db.returnRowIndexForValue(searchFutureTbl, 3 , searchFutureTxt.getText());
                double paidNew = (double) searchFutureTbl.getValueAt(rowIndex, 1) + Double.parseDouble(updateFuturePaidTxt.getText());
                double remenderNew = (double) searchFutureTbl.getValueAt(rowIndex, 0) - Double.parseDouble(updateFuturePaidTxt.getText());
                searchFutureTbl.setValueAt(paidNew, rowIndex, 1);
                searchFutureTbl.setValueAt(remenderNew, rowIndex, 0);

                JOptionPane.showMessageDialog(null, "تم اضافة المبلغ بنجاح ", "Success", 2, new ImageIcon("Ok.png"));
                updateFuturePaidConfBtn.setVisible(false);
                updateFuturePaidLbl.setVisible(false);
                updateFuturePaidTxt.setVisible(false);
                updateFuturePaidBtn.setVisible(false);
                updateFuturePaidTxt.setText(null);

            }
            
        } catch (SQLException ex) {
            Logger.getLogger(SearchCompany.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(new JPanel(), "من فضلك ادخل المبلغ بالارقام", "Error", JOptionPane.ERROR_MESSAGE);
            updateFuturePaidTxt.setText(null);
        }
    }//GEN-LAST:event_updateFuturePaidConfBtnActionPerformed

    private void updateFuturePaidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFuturePaidTxtActionPerformed
        updateFuturePaidConfBtnActionPerformed(evt);
    }//GEN-LAST:event_updateFuturePaidTxtActionPerformed

    private void updateFuturePaidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFuturePaidBtnActionPerformed
        updateFuturePaidLbl.setVisible(true);
        updateFuturePaidTxt.setVisible(true);
        updateFuturePaidConfBtn.setVisible(true);
    }//GEN-LAST:event_updateFuturePaidBtnActionPerformed

    private void futureMainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_futureMainBtnActionPerformed
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_futureMainBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
       new MainPage().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void searchFutureTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFutureTblMouseClicked
        int  srow = searchFutureTbl.getSelectedRow();
                if(srow>-1)
                {
                    searchFutureTbl.setSelectionBackground(Color.PINK);
                    String phone = searchFutureTbl.getValueAt(srow, 3).toString() ;
                    searchFutureTxt.setText(phone) ;
                    updateFuturePaidBtn.setVisible(true);
                    
                }
    }//GEN-LAST:event_searchFutureTblMouseClicked

    private void searchFutureTblKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFutureTblKeyTyped
         int  srow = searchFutureTbl.getSelectedRow();
                if(srow>-1)
                {
                    searchFutureTbl.setSelectionBackground(Color.PINK);
                    String phone = searchFutureTbl.getValueAt(srow, 3).toString() ;
                    searchFutureTxt.setText(phone) ;
                    updateFuturePaidBtn.setVisible(true);
                    
                }
    }//GEN-LAST:event_searchFutureTblKeyTyped
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Future.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Future.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Future.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Future.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Future().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton futureMainBtn;
    private javax.swing.JScrollPane jScrollPaneFuture;
    private javax.swing.JButton noSearchFutureBtn;
    private javax.swing.JButton searchFutureBtn;
    private javax.swing.JComboBox searchFutureCBox;
    private javax.swing.JLabel searchFutureLbl;
    private javax.swing.JTable searchFutureTbl;
    private javax.swing.JTextField searchFutureTxt;
    private javax.swing.JButton updateFutureBtn;
    private javax.swing.JButton updateFuturePaidBtn;
    private javax.swing.JButton updateFuturePaidConfBtn;
    private javax.swing.JLabel updateFuturePaidLbl;
    private javax.swing.JTextField updateFuturePaidTxt;
    // End of variables declaration//GEN-END:variables
}
