
import java.awt.Color;
import java.io.ByteArrayInputStream;
import java.io.ObjectInputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamed
 */
public class FwaterAgel extends javax.swing.JFrame {

    DB db = new DB() ;
    DefaultTableModel model ;
    ResultSet rset;
    String query;
    
    public FwaterAgel() {
        initComponents();
        
        Object[] row = new Object[5] ;
        query = "Select * from bill where client_mob = '" + Future.phone + "'"  ;
        try 
        {
            rset = DB.stmt.executeQuery(query) ;
            if (!rset.next())
            {
                 JOptionPane.showMessageDialog(null, "لا يوجد فواتير");
                                         
            }
            
            else
            {
                do
                {
                  row[4] = rset.getString(1) ;
                  row[3] = rset.getString(3) ;
                  row[2] = rset.getDouble(2) ;
                  row[1] = rset.getDouble(6) ;
                  row[0] = rset.getDouble(7) ;
                
                  model = (DefaultTableModel) searchFwaterTbl.getModel() ;
                  model.addRow(row) ;
                } while(rset.next());
            }
        }
        
        catch (SQLException ex) 
        {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        searchFwaterTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        searchFwaterTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "المتبقى", "المدفوع", "المبلغ الكلى", "التاريخ", "رقم الفاتورة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchFwaterTbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        searchFwaterTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFwaterTblMouseClicked(evt);
            }
        });
        searchFwaterTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFwaterTblKeyTyped(evt);
            }
        });
        jScrollPane.setViewportView(searchFwaterTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFwaterTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFwaterTblMouseClicked
        
        int  srow = searchFwaterTbl.getSelectedRow();
                if(srow>-1)
                {
                    searchFwaterTbl.setSelectionBackground(Color.PINK);
                    String billNo = searchFwaterTbl.getValueAt(srow, 4).toString() ;
                    query = "Select details from bill where ID =" + billNo ;
                    try {
                           rset = DB.stmt.executeQuery(query);
                           rset.next();
                           //  obj = rs.getObject(1) ; 
                           byte[] buf = rset.getBytes(1);
                           ObjectInputStream objectIn = null;
	                   if (buf != null)
		           	objectIn = new ObjectInputStream(new ByteArrayInputStream(buf));

		           Object deSerializedObject = objectIn.readObject();
                           new Bill_details((DefaultTableModel) deSerializedObject).setVisible(true) ;
            
                        } 
                    
        catch(Exception ex)
        {
             Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
        }
                    
                }//enf if
    }//GEN-LAST:event_searchFwaterTblMouseClicked

    private void searchFwaterTblKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFwaterTblKeyTyped
        
        int  srow = searchFwaterTbl.getSelectedRow();
                if(srow>-1)
                {
                    searchFwaterTbl.setSelectionBackground(Color.PINK);
                    String billNo = searchFwaterTbl.getValueAt(srow, 4).toString() ;
                    query = "Select details from bill where ID =" + billNo ;
                    try {
                           rset = DB.stmt.executeQuery(query);
                           rset.next();
                           //  obj = rs.getObject(1) ; 
                           byte[] buf = rset.getBytes(1);
                           ObjectInputStream objectIn = null;
	                   if (buf != null)
		           	objectIn = new ObjectInputStream(new ByteArrayInputStream(buf));

		           Object deSerializedObject = objectIn.readObject();
                           new Bill_details((DefaultTableModel) deSerializedObject).setVisible(true) ;
            
                        } 
                    
        catch(Exception ex)
        {
             Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
        }
                    
                }//enf if
    }//GEN-LAST:event_searchFwaterTblKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FwaterAgel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FwaterAgel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FwaterAgel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FwaterAgel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FwaterAgel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable searchFwaterTbl;
    // End of variables declaration//GEN-END:variables
}
