/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Mohamed
 */
public class MainPage extends javax.swing.JFrame {

    
    
    public MainPage() {
        initComponents();
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSearchLbl = new javax.swing.JLabel();
        mainSearchCBox = new javax.swing.JComboBox();
        mainSearchBtn = new javax.swing.JButton();
        mainSellBtn = new javax.swing.JButton();
        mainReprBtn = new javax.swing.JButton();
        mainAddBtn = new javax.swing.JButton();
        mainLogOutBtn = new javax.swing.JButton();
        mainAddBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 500));
        getContentPane().setLayout(null);

        mainSearchLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainSearchLbl.setText("بحث عن:");
        getContentPane().add(mainSearchLbl);
        mainSearchLbl.setBounds(294, 26, 61, 43);

        mainSearchCBox.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        mainSearchCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "منتج", "شركة", "فاتورة", "تصليحات" }));
        mainSearchCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSearchCBoxActionPerformed(evt);
            }
        });
        getContentPane().add(mainSearchCBox);
        mainSearchCBox.setBounds(180, 29, 110, 40);

        mainSearchBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mainSearchBtn.setText("بحث");
        mainSearchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSearchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainSearchBtn);
        mainSearchBtn.setBounds(80, 30, 80, 40);

        mainSellBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainSellBtn.setText("بيع");
        mainSellBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainSellBtn.setPreferredSize(new java.awt.Dimension(50, 25));
        getContentPane().add(mainSellBtn);
        mainSellBtn.setBounds(131, 113, 159, 47);

        mainReprBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainReprBtn.setText("تصليح");
        mainReprBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainReprBtn.setPreferredSize(new java.awt.Dimension(50, 25));
        mainReprBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainReprBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainReprBtn);
        mainReprBtn.setBounds(131, 178, 159, 45);

        mainAddBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainAddBtn.setText("شركـات");
        mainAddBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainAddBtn.setPreferredSize(new java.awt.Dimension(50, 25));
        mainAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainAddBtn);
        mainAddBtn.setBounds(130, 250, 159, 47);

        mainLogOutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainLogOutBtn.setText("خروج");
        mainLogOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainLogOutBtn.setPreferredSize(new java.awt.Dimension(50, 25));
        mainLogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLogOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainLogOutBtn);
        mainLogOutBtn.setBounds(131, 393, 159, 49);

        mainAddBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainAddBtn1.setText("اضافة");
        mainAddBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainAddBtn1.setPreferredSize(new java.awt.Dimension(50, 25));
        mainAddBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(mainAddBtn1);
        mainAddBtn1.setBounds(131, 319, 159, 47);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSearchBtnActionPerformed
        if (mainSearchCBox.getSelectedIndex()== 0) 
        {
            this.dispose() ;
            SearchProduct product  = new SearchProduct() ;
            product.setVisible(true) ;
        }
        else if (mainSearchCBox.getSelectedIndex()== 1) 
        {
            this.dispose() ;
            SearchCompany company = new SearchCompany() ;
            company.setVisible(true) ;
        }
        else if (mainSearchCBox.getSelectedIndex()== 2) 
        {
            this.dispose() ;
            SearchBill bill = new SearchBill() ;
            bill.setVisible(true) ;
        }
        else if (mainSearchCBox.getSelectedIndex()== 3) 
        {
            this.dispose() ;
            SearchRepair repair = new SearchRepair() ;
            repair.setVisible(true) ;
        }
    }//GEN-LAST:event_mainSearchBtnActionPerformed

    private void mainLogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainLogOutBtnActionPerformed
         this.dispose() ;
          Login log  = new Login() ;
          log.setVisible(true) ;
    }//GEN-LAST:event_mainLogOutBtnActionPerformed

    private void mainReprBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainReprBtnActionPerformed
        this.dispose();
        estlam es = new estlam();
        es.setVisible(true);
    }//GEN-LAST:event_mainReprBtnActionPerformed

    private void mainSearchCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSearchCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainSearchCBoxActionPerformed

    private void mainAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddBtnActionPerformed
        this.dispose() ;
        add ad = new add() ;
        ad.setVisible(true) ;
    }//GEN-LAST:event_mainAddBtnActionPerformed

    private void mainAddBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainAddBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mainAddBtn;
    private javax.swing.JButton mainAddBtn1;
    private javax.swing.JButton mainLogOutBtn;
    private javax.swing.JButton mainReprBtn;
    private javax.swing.JButton mainSearchBtn;
    private javax.swing.JComboBox mainSearchCBox;
    private javax.swing.JLabel mainSearchLbl;
    private javax.swing.JButton mainSellBtn;
    // End of variables declaration//GEN-END:variables
}
