
import java.awt.Color;


//import java.time.LocalDateTime;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Mohamed
 */
public class MainPage extends javax.swing.JFrame {

    
    
    public MainPage() {
        initComponents();
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSearchLbl = new javax.swing.JLabel();
        mainSearchCBox = new javax.swing.JComboBox();
        mainSearchBtn = new javax.swing.JButton();
        mainSellBtn = new javax.swing.JButton();
        mainReprBtn = new javax.swing.JButton();
        mainAddBtn = new javax.swing.JButton();
        mainLogOutBtn = new javax.swing.JButton();
        mainAddBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 500));
        getContentPane().setLayout(null);

        mainSearchLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainSearchLbl.setText("بحث عن:");
        getContentPane().add(mainSearchLbl);
        mainSearchLbl.setBounds(294, 26, 61, 43);

        mainSearchCBox.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        mainSearchCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "منتج", "شركة", "فاتورة", "تصليحات" }));
        mainSearchCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSearchCBoxActionPerformed(evt);
            }
        });
        getContentPane().add(mainSearchCBox);
        mainSearchCBox.setBounds(180, 29, 110, 40);

        mainSearchBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mainSearchBtn.setText("بحث");
        mainSearchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainSearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainSearchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainSearchBtnMouseExited(evt);
            }
        });
        mainSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSearchBtnActionPerformed(evt);
            }
        });
        mainSearchBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainSearchBtnKeyPressed(evt);
            }
        });
        getContentPane().add(mainSearchBtn);
        mainSearchBtn.setBounds(80, 30, 80, 40);

        mainSellBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainSellBtn.setText("بيع");
        mainSellBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainSellBtn.setPreferredSize(new java.awt.Dimension(50, 25));
        mainSellBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainSellBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainSellBtnMouseExited(evt);
            }
        });
        mainSellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSellBtnActionPerformed(evt);
            }
        });
        mainSellBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainSellBtnKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mainSellBtnKeyTyped(evt);
            }
        });
        getContentPane().add(mainSellBtn);
        mainSellBtn.setBounds(131, 113, 159, 47);

        mainReprBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainReprBtn.setText("تصليح");
        mainReprBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainReprBtn.setPreferredSize(new java.awt.Dimension(50, 25));
        mainReprBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainReprBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainReprBtnMouseExited(evt);
            }
        });
        mainReprBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainReprBtnActionPerformed(evt);
            }
        });
        mainReprBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainReprBtnKeyPressed(evt);
            }
        });
        getContentPane().add(mainReprBtn);
        mainReprBtn.setBounds(131, 178, 159, 45);

        mainAddBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainAddBtn.setText("شركـات");
        mainAddBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainAddBtn.setPreferredSize(new java.awt.Dimension(50, 25));
        mainAddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainAddBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainAddBtnMouseExited(evt);
            }
        });
        mainAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddBtnActionPerformed(evt);
            }
        });
        mainAddBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainAddBtnKeyPressed(evt);
            }
        });
        getContentPane().add(mainAddBtn);
        mainAddBtn.setBounds(130, 250, 159, 47);

        mainLogOutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainLogOutBtn.setText("خروج");
        mainLogOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainLogOutBtn.setPreferredSize(new java.awt.Dimension(50, 25));
        mainLogOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainLogOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainLogOutBtnMouseExited(evt);
            }
        });
        mainLogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLogOutBtnActionPerformed(evt);
            }
        });
        mainLogOutBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainLogOutBtnKeyPressed(evt);
            }
        });
        getContentPane().add(mainLogOutBtn);
        mainLogOutBtn.setBounds(131, 393, 159, 49);

        mainAddBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainAddBtn1.setText("اضافة");
        mainAddBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainAddBtn1.setPreferredSize(new java.awt.Dimension(50, 25));
        mainAddBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainAddBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainAddBtn1MouseExited(evt);
            }
        });
        mainAddBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddBtn1ActionPerformed(evt);
            }
        });
        mainAddBtn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainAddBtn1KeyPressed(evt);
            }
        });
        getContentPane().add(mainAddBtn1);
        mainAddBtn1.setBounds(131, 319, 159, 47);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSearchBtnActionPerformed
        if (mainSearchCBox.getSelectedIndex()== 0) 
        {
            this.dispose() ;
            SearchProduct product  = new SearchProduct() ;
            product.setVisible(true) ;
        }
        else if (mainSearchCBox.getSelectedIndex()== 1) 
        {
            this.dispose() ;
            SearchCompany company = new SearchCompany() ;
            company.setVisible(true) ;
        }
        else if (mainSearchCBox.getSelectedIndex()== 2) 
        {
            this.dispose() ;
            SearchBill bill = new SearchBill() ;
            bill.setVisible(true) ;
        }
        else if (mainSearchCBox.getSelectedIndex()== 3) 
        {
            this.dispose() ;
            SearchRepair repair = new SearchRepair() ;
            repair.setVisible(true) ;
        }
    }//GEN-LAST:event_mainSearchBtnActionPerformed

    private void mainLogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainLogOutBtnActionPerformed
         this.dispose() ;
          Login log  = new Login() ;
          log.setVisible(true) ;
    }//GEN-LAST:event_mainLogOutBtnActionPerformed

    private void mainReprBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainReprBtnActionPerformed
        this.dispose();
        estlam es = new estlam();
        es.setVisible(true);
    }//GEN-LAST:event_mainReprBtnActionPerformed

    private void mainSearchCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSearchCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainSearchCBoxActionPerformed

    private void mainAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddBtnActionPerformed
        this.dispose() ;
        addcompany ad = new addcompany();
        ad.setVisible(true) ;
    }//GEN-LAST:event_mainAddBtnActionPerformed

    private void mainAddBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddBtn1ActionPerformed
        
        add ad = new add();
        this.dispose();
        ad.setVisible(true);
    }//GEN-LAST:event_mainAddBtn1ActionPerformed

    private void mainSellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSellBtnActionPerformed
        
        bill b = new bill();
        this.dispose();
        b.setVisible(true);
        
    }//GEN-LAST:event_mainSellBtnActionPerformed

    private void mainSellBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainSellBtnKeyPressed
        bill b = new bill();
        this.dispose();
        b.setVisible(true);
    }//GEN-LAST:event_mainSellBtnKeyPressed

    private void mainSellBtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainSellBtnKeyTyped
        
    }//GEN-LAST:event_mainSellBtnKeyTyped

    private void mainSellBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainSellBtnMouseEntered
        mainSellBtn.setBackground(Color.green);
    }//GEN-LAST:event_mainSellBtnMouseEntered

    private void mainSellBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainSellBtnMouseExited
        mainSellBtn.setBackground(null);
    }//GEN-LAST:event_mainSellBtnMouseExited

    private void mainReprBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainReprBtnMouseEntered
        mainReprBtn.setBackground(Color.green);
    }//GEN-LAST:event_mainReprBtnMouseEntered

    private void mainReprBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainReprBtnMouseExited
        mainReprBtn.setBackground(null);
    }//GEN-LAST:event_mainReprBtnMouseExited

    private void mainAddBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainAddBtnMouseEntered
        mainAddBtn.setBackground(Color.green);
    }//GEN-LAST:event_mainAddBtnMouseEntered

    private void mainAddBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainAddBtnMouseExited
        mainAddBtn.setBackground(null);
    }//GEN-LAST:event_mainAddBtnMouseExited

    private void mainAddBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainAddBtn1MouseEntered
        mainAddBtn1.setBackground(Color.green);
    }//GEN-LAST:event_mainAddBtn1MouseEntered

    private void mainAddBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainAddBtn1MouseExited
        mainAddBtn1.setBackground(null);
    }//GEN-LAST:event_mainAddBtn1MouseExited

    private void mainLogOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainLogOutBtnMouseEntered
        mainLogOutBtn.setBackground(Color.green);
    }//GEN-LAST:event_mainLogOutBtnMouseEntered

    private void mainLogOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainLogOutBtnMouseExited
        mainLogOutBtn.setBackground(null);
    }//GEN-LAST:event_mainLogOutBtnMouseExited

    private void mainSearchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainSearchBtnMouseEntered
        mainSearchBtn.setBackground(Color.green);
    }//GEN-LAST:event_mainSearchBtnMouseEntered

    private void mainSearchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainSearchBtnMouseExited
        mainSearchBtn.setBackground(null);
    }//GEN-LAST:event_mainSearchBtnMouseExited

    private void mainSearchBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainSearchBtnKeyPressed
        if (mainSearchCBox.getSelectedIndex()== 0) 
        {
            this.dispose() ;
            SearchProduct product  = new SearchProduct() ;
            product.setVisible(true) ;
        }
        else if (mainSearchCBox.getSelectedIndex()== 1) 
        {
            this.dispose() ;
            SearchCompany company = new SearchCompany() ;
            company.setVisible(true) ;
        }
        else if (mainSearchCBox.getSelectedIndex()== 2) 
        {
            this.dispose() ;
            SearchBill bill = new SearchBill() ;
            bill.setVisible(true) ;
        }
        else if (mainSearchCBox.getSelectedIndex()== 3) 
        {
            this.dispose() ;
            SearchRepair repair = new SearchRepair() ;
            repair.setVisible(true) ;
        }
    }//GEN-LAST:event_mainSearchBtnKeyPressed

    private void mainReprBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainReprBtnKeyPressed
        this.dispose();
        estlam es = new estlam();
        es.setVisible(true);
    }//GEN-LAST:event_mainReprBtnKeyPressed

    private void mainAddBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainAddBtnKeyPressed
        this.dispose() ;
        addcompany ad = new addcompany();
        ad.setVisible(true) ;
    }//GEN-LAST:event_mainAddBtnKeyPressed

    private void mainAddBtn1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainAddBtn1KeyPressed
        add ad = new add();
        this.dispose();
        ad.setVisible(true);
    }//GEN-LAST:event_mainAddBtn1KeyPressed

    private void mainLogOutBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainLogOutBtnKeyPressed
          this.dispose() ;
          Login log  = new Login() ;
          log.setVisible(true) ;
    }//GEN-LAST:event_mainLogOutBtnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mainAddBtn;
    private javax.swing.JButton mainAddBtn1;
    private javax.swing.JButton mainLogOutBtn;
    private javax.swing.JButton mainReprBtn;
    private javax.swing.JButton mainSearchBtn;
    private javax.swing.JComboBox mainSearchCBox;
    private javax.swing.JLabel mainSearchLbl;
    private javax.swing.JButton mainSellBtn;
    // End of variables declaration//GEN-END:variables
}
