/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import sun.awt.FocusingTextField;

/**
 *
 * @author Mohamed
 */
public class SearchCompany extends javax.swing.JFrame {

    DB dbase = new DB() ;
    DefaultTableModel model ;
    ResultSet rset;
    String query;
    
    public SearchCompany() {
        initComponents();
        DB.initializeconnection();
        
        updatePaidBtn.hide();
        updatePaidConfBtn.hide();
        updatePaidLbl.hide();
        updatePaidTxt.hide();
        updateTelBtn.hide();
        updateTelConfBtn.hide();
        updateTelLbl.hide();
        updateTelTxt.hide();
        
         query = "Select name from company"  ;
         try 
        {
            rset = DB.stmt.executeQuery(query) ;
            if (!rset.next())
            {
                JOptionPane.showMessageDialog(null,"لا يوجد بيانات");
            }
            
            else
            {
                do
                { 
                    jComboBox1.addItem(rset.getString(1));
                    jComboBox2.addItem(rset.getString(1));
                }
                while(rset.next());
                 
            }
            
            
        }
        
        catch (SQLException ex) 
        {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void search(JTextField text)
    {
        if(text.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"من فضلك ادخل اسم الشركة");
           
        }
        
        else
        {
        Object[] row = new Object[4] ;
        query = "Select * from company where name = '" + text.getText() + "'" ;
        
        try 
        {
            rset = DB.stmt.executeQuery(query) ;
            if (!rset.next())
            {
                text.setText(null) ;
                int dialogResult = JOptionPane.showConfirmDialog(new JPanel(), "الشركة غير مسجلة..هل ترغب فى اضافتها ؟", "Error", JOptionPane.YES_NO_OPTION);
                if(dialogResult == JOptionPane.YES_OPTION)
                {
                    new addcompany().setVisible(true);
                    this.dispose();
                }
            }
            
            else
            {
                do
                {
                  row[3] = rset.getString(1) ;
                  row[2] = rset.getString(2) ;
                  row[1] = rset.getDouble(3) ;
                  row[0] = rset.getDouble(4) ;
                
                  model = (DefaultTableModel) searchCompTbl.getModel() ;
                  model.addRow(row) ;
                } while(rset.next());
            }
        }
        
        catch (SQLException ex) 
        {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
      }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchCompLbl = new javax.swing.JLabel();
        searchCompTxt = new javax.swing.JTextField();
        searchCompBtn = new javax.swing.JButton();
        noSearchCompBtn = new javax.swing.JButton();
        jScrollPaneComp = new javax.swing.JScrollPane();
        searchCompTbl = new javax.swing.JTable();
        compMainBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        updateCompTxt = new javax.swing.JTextField();
        updateCompLbl = new javax.swing.JLabel();
        noupdateCompBtn = new javax.swing.JButton();
        updateCompBtn = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        updatePaidBtn = new javax.swing.JButton();
        updateTelBtn = new javax.swing.JButton();
        updatePaidLbl = new javax.swing.JLabel();
        updateTelLbl = new javax.swing.JLabel();
        updatePaidTxt = new javax.swing.JTextField();
        updateTelTxt = new javax.swing.JTextField();
        updatePaidConfBtn = new javax.swing.JButton();
        updateTelConfBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(850, 600));
        setResizable(false);

        searchCompLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchCompLbl.setText("اسم الشركة:");

        searchCompTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCompTxtActionPerformed(evt);
            }
        });

        searchCompBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchCompBtn.setText("بحث");
        searchCompBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchCompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCompBtnActionPerformed(evt);
            }
        });

        noSearchCompBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        noSearchCompBtn.setText("الغاء");
        noSearchCompBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noSearchCompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSearchCompBtnActionPerformed(evt);
            }
        });

        searchCompTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "المتبقى", "المدفوع", "رقم التليفون", "اسم الشركة"
            }
        ));
        searchCompTbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPaneComp.setViewportView(searchCompTbl);

        compMainBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        compMainBtn.setText("القائمة الرئيسية");
        compMainBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        compMainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compMainBtnActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        updateCompTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCompTxtActionPerformed(evt);
            }
        });

        updateCompLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateCompLbl.setText("تحديث بيانات شركة:");

        noupdateCompBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        noupdateCompBtn.setText("الغاء");
        noupdateCompBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noupdateCompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noupdateCompBtnActionPerformed(evt);
            }
        });

        updateCompBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateCompBtn.setText("تحديث");
        updateCompBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateCompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCompBtnActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        updatePaidBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatePaidBtn.setText("دفع للشركة");
        updatePaidBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatePaidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePaidBtnActionPerformed(evt);
            }
        });

        updateTelBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateTelBtn.setText("تغيير رقم التليفون");
        updateTelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateTelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTelBtnActionPerformed(evt);
            }
        });

        updatePaidLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatePaidLbl.setText("المبلغ المدفوع: ");

        updateTelLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateTelLbl.setText("رقم التليفون الجديد:");

        updatePaidTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatePaidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePaidTxtActionPerformed(evt);
            }
        });

        updateTelTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateTelTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTelTxtActionPerformed(evt);
            }
        });

        updatePaidConfBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatePaidConfBtn.setText("تأكيد");
        updatePaidConfBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatePaidConfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePaidConfBtnActionPerformed(evt);
            }
        });

        updateTelConfBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateTelConfBtn.setText("تأكيد");
        updateTelConfBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateTelConfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTelConfBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneComp, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(compMainBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noupdateCompBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateCompBtn))
                            .addComponent(updateCompTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(updateCompLbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchCompTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(noSearchCompBtn)
                                .addGap(56, 56, 56)
                                .addComponent(searchCompBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCompLbl)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateTelConfBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateTelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updatePaidConfBtn)
                                .addGap(37, 37, 37)
                                .addComponent(updatePaidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updatePaidLbl)
                            .addComponent(updateTelLbl))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(updateTelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatePaidBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateCompTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateCompLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noupdateCompBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateCompBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchCompTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchCompLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noSearchCompBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchCompBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addComponent(jScrollPaneComp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updatePaidTxt)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatePaidConfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(updatePaidBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updatePaidLbl)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTelLbl)
                    .addComponent(updateTelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTelConfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(compMainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchCompTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCompTxtActionPerformed
        searchCompBtnActionPerformed(evt) ;
    }//GEN-LAST:event_searchCompTxtActionPerformed

    private void searchCompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCompBtnActionPerformed
        if(!dbase.ValueIsExist(searchCompTbl , 3 , searchCompTxt.getText()))
        {
            search(searchCompTxt) ;
        }
     
        else
        {
            JOptionPane.showMessageDialog(null,"تم البحث بالفعل");
        }
            
    }//GEN-LAST:event_searchCompBtnActionPerformed

    private void noSearchCompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSearchCompBtnActionPerformed
        searchCompTxt.setText(null);
        model.setRowCount(0);
        
    }//GEN-LAST:event_noSearchCompBtnActionPerformed

    private void compMainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compMainBtnActionPerformed
        
        new MainPage().setVisible(true) ;
        this.dispose();
    }//GEN-LAST:event_compMainBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        searchCompTxt.setText(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void updateCompTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCompTxtActionPerformed
        updateCompBtnActionPerformed(evt) ;
    }//GEN-LAST:event_updateCompTxtActionPerformed

    private void noupdateCompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noupdateCompBtnActionPerformed
        updateCompTxt.setText(null);
        updatePaidBtn.setVisible(false);
        updateTelBtn.setVisible(false);
        updatePaidConfBtn.setVisible(false);
        updatePaidLbl.setVisible(false);
        updatePaidTxt.setVisible(false);
        updateTelConfBtn.setVisible(false);
        updateTelLbl.setVisible(false);
        updateTelTxt.setVisible(false);
    }//GEN-LAST:event_noupdateCompBtnActionPerformed

    private void updateCompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCompBtnActionPerformed
        if(!dbase.ValueIsExist(searchCompTbl , 3 , updateCompTxt.getText()))
        {
            search(updateCompTxt) ;
        }
        if(dbase.ValueIsExist(searchCompTbl , 3 , updateCompTxt.getText()))
        {
            updatePaidBtn.setVisible(true);
            updateTelBtn.setVisible(true);
        }
        
    }//GEN-LAST:event_updateCompBtnActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        updateCompTxt.setText(jComboBox2.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void updatePaidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePaidBtnActionPerformed
        updatePaidLbl.setVisible(true);
        updatePaidTxt.setVisible(true);
        updatePaidConfBtn.setVisible(true);
    }//GEN-LAST:event_updatePaidBtnActionPerformed

    private void updateTelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTelBtnActionPerformed
        updateTelLbl.setVisible(true);
        updateTelTxt.setVisible(true);
        updateTelConfBtn.setVisible(true);
    }//GEN-LAST:event_updateTelBtnActionPerformed

    private void updateTelTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTelTxtActionPerformed
        updateTelConfBtnActionPerformed(evt) ;
    }//GEN-LAST:event_updateTelTxtActionPerformed

    private void updatePaidConfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePaidConfBtnActionPerformed
        //query = "Select * from company where name = '" + updateCompTxt.getText() + "'" ;
        try 
        {
            //rset = DB.stmt.executeQuery(query) ;
            //if (!rset.next())
            //{
                //JOptionPane.showMessageDialog(null,"no search result, company name may be wrong ");
            //}
            
            //else
            //{
                //double newPaid = Double.parseDouble(updatePaidTxt.getText()) + Double.parseDouble(rset.getString(3));
                //double newReminder = Double.parseDouble(rset.getString(4)) - Double.parseDouble(updatePaidTxt.getText());
                String updateQuery = "UPDATE company SET paid = paid + '" + Double.parseDouble(updatePaidTxt.getText()) + "' , remender = remender - '" + Double.parseDouble(updatePaidTxt.getText()) + "' WHERE name = '" + updateCompTxt.getText() + "'" ;
                int rowCount = DB.stmt.executeUpdate(updateQuery);
                if(rowCount == 0)
                {
                    JOptionPane.showMessageDialog(new JPanel(), "خطأ فى تحديث البانات", "Error", JOptionPane.ERROR_MESSAGE);
                    updatePaidTxt.setText(null);
                }
                else
                {
                    int rowIndex = dbase.returnRowIndexForValue(searchCompTbl, 3 , updateCompTxt.getText()) ;
                    double paidNew = (double)searchCompTbl.getValueAt(rowIndex, 1) + Double.parseDouble(updatePaidTxt.getText()) ;
                    double remenderNew = (double)searchCompTbl.getValueAt(rowIndex, 0) - Double.parseDouble(updatePaidTxt.getText()) ;
                    searchCompTbl.setValueAt(paidNew , rowIndex , 1);
                    searchCompTbl.setValueAt(remenderNew , rowIndex , 0);
                    
                    updatePaidConfBtn.setVisible(false);
                    updatePaidLbl.setVisible(false);
                    updatePaidTxt.setVisible(false);
                    updatePaidTxt.setText(null);
                            
                    JOptionPane.showMessageDialog(null, "تم اضافة المبلغ بنجاح ", "Success", 2, new ImageIcon("Ok.png"));
                }
            //}
        } 
        
        catch (SQLException ex) 
        {
            Logger.getLogger(SearchCompany.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(new JPanel(), "من فضلك ادخل المبلغ بالارقام", "Error", JOptionPane.ERROR_MESSAGE);
            updatePaidTxt.setText(null);
        }
    }//GEN-LAST:event_updatePaidConfBtnActionPerformed

    private void updateTelConfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTelConfBtnActionPerformed
        
        query = "UPDATE company SET tel = '" + updateTelTxt.getText() + "' WHERE name = '" + updateCompTxt.getText() + "'" ;
        try 
        {
            int rowCount = DB.stmt.executeUpdate(query);
            if(rowCount == 0)
                {
                    JOptionPane.showMessageDialog(new JPanel(), "خطأ فى تحديث البانات", "Error", JOptionPane.ERROR_MESSAGE);
                    updateTelTxt.setText(null);
                }
            
            else
                {
                    searchCompTbl.setValueAt(updateTelTxt.getText() , dbase.returnRowIndexForValue(searchCompTbl, 3 , updateCompTxt.getText() ) , 2);
                    
                    updateTelConfBtn.setVisible(false);
                    updateTelLbl.setVisible(false);
                    updateTelTxt.setVisible(false);
                    updateTelTxt.setText(null);
                    
                    JOptionPane.showMessageDialog(null, "تم التعديل بنجاح ", "Success", 2, new ImageIcon("Ok.png"));
                }
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(SearchCompany.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "من فضلك ادخل رقم تليفون صحيح", "Error", JOptionPane.ERROR_MESSAGE);
            updateTelTxt.setText(null);
        }
    }//GEN-LAST:event_updateTelConfBtnActionPerformed

    private void updatePaidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePaidTxtActionPerformed
        updatePaidConfBtnActionPerformed(evt) ;
    }//GEN-LAST:event_updatePaidTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not availanoSearchCompBtn the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SearchCompany().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compMainBtn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JScrollPane jScrollPaneComp;
    private javax.swing.JButton noSearchCompBtn;
    private javax.swing.JButton noupdateCompBtn;
    private javax.swing.JButton searchCompBtn;
    private javax.swing.JLabel searchCompLbl;
    private javax.swing.JTable searchCompTbl;
    private javax.swing.JTextField searchCompTxt;
    private javax.swing.JButton updateCompBtn;
    private javax.swing.JLabel updateCompLbl;
    private javax.swing.JTextField updateCompTxt;
    private javax.swing.JButton updatePaidBtn;
    private javax.swing.JButton updatePaidConfBtn;
    private javax.swing.JLabel updatePaidLbl;
    private javax.swing.JTextField updatePaidTxt;
    private javax.swing.JButton updateTelBtn;
    private javax.swing.JButton updateTelConfBtn;
    private javax.swing.JLabel updateTelLbl;
    private javax.swing.JTextField updateTelTxt;
    // End of variables declaration//GEN-END:variables
}
