/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohamed
 */
public class SearchCompany extends javax.swing.JFrame {

   DB dbase = new DB() ;
    DefaultTableModel model ;
    
    public SearchCompany() {
        initComponents();
        DB.initializeconnection();
        String query = "Select name from company"  ;
         try 
        {
            dbase.rset = DB.stmt.executeQuery(query) ;
            System.out.println(query);
            if (!dbase.rset.next())
            {
                JOptionPane.showMessageDialog(null,"no search result, company may be not registered ");
            }
            
            else
            {
                do
                { 
                    jComboBox1.addItem(dbase.rset.getString(1));
                    System.out.println(dbase.rset.getString(1));
                }
                while(dbase.rset.next());
                 
            }
            
            
        }
        
        catch (SQLException ex) 
        {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error "+ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchCompLbl = new javax.swing.JLabel();
        searchCompTxt = new javax.swing.JTextField();
        searchCompBtn = new javax.swing.JButton();
        noSearchCompBtn = new javax.swing.JButton();
        jScrollPaneComp = new javax.swing.JScrollPane();
        searchCompTbl = new javax.swing.JTable();
        compMainBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        searchCompLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchCompLbl.setText("اسم الشركة:");

        searchCompTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCompTxtActionPerformed(evt);
            }
        });

        searchCompBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchCompBtn.setText("بحث");
        searchCompBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchCompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCompBtnActionPerformed(evt);
            }
        });

        noSearchCompBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        noSearchCompBtn.setText("الغاء");
        noSearchCompBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noSearchCompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSearchCompBtnActionPerformed(evt);
            }
        });

        searchCompTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "المتبقى", "المدفوع", "رقم التليفون", "اسم الشركة"
            }
        ));
        searchCompTbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPaneComp.setViewportView(searchCompTbl);

        compMainBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        compMainBtn.setText("القائمة الرئيسية");
        compMainBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        compMainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compMainBtnActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noSearchCompBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchCompBtn))
                            .addComponent(searchCompTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchCompLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(compMainBtn)
                        .addGap(171, 171, 171))))
            .addComponent(jScrollPaneComp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCompLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCompTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCompBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noSearchCompBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPaneComp, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(compMainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchCompTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCompTxtActionPerformed
        
    }//GEN-LAST:event_searchCompTxtActionPerformed

    private void searchCompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCompBtnActionPerformed
        Object[] row = new Object[4] ;
        String query = "Select * from company where name = '" + searchCompTxt.getText() + "'" ;
        
        try 
        {
            dbase.rset = DB.stmt.executeQuery(query) ;
            System.out.println(query);
            if (!dbase.rset.next())
            {
                JOptionPane.showMessageDialog(null,"no search result, company may be not registered ");
            }
            
            else
            {
                do
                {
                  row[3] = dbase.rset.getString(1) ;
                  row[2] = dbase.rset.getString(2) ;
                  row[1] = dbase.rset.getDouble(3) ;
                  row[0] = dbase.rset.getDouble(4) ;
                
                  model = (DefaultTableModel) searchCompTbl.getModel() ;
                  model.addRow(row) ;
                } while(dbase.rset.next());
            }
        }
        
        catch (SQLException ex) 
        {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error "+ex.getMessage());
        }
        
     
    }//GEN-LAST:event_searchCompBtnActionPerformed

    private void noSearchCompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSearchCompBtnActionPerformed
        searchCompTxt.setText(null);
        model.setRowCount(0);
        
    }//GEN-LAST:event_noSearchCompBtnActionPerformed

    private void compMainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compMainBtnActionPerformed
        this.dispose();
        MainPage main = new MainPage() ;
        main.setVisible(true) ;
    }//GEN-LAST:event_compMainBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        searchCompTxt.setText(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not availanoSearchCompBtn the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.searchcompLblgging.Logger.getLogger(SearchCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SearchCompany().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compMainBtn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPaneComp;
    private javax.swing.JButton noSearchCompBtn;
    private javax.swing.JButton searchCompBtn;
    private javax.swing.JLabel searchCompLbl;
    private javax.swing.JTable searchCompTbl;
    private javax.swing.JTextField searchCompTxt;
    // End of variables declaration//GEN-END:variables
}
