/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mohamed
 */
public class SearchProduct extends javax.swing.JFrame {

    DB dbase = new DB() ;
    DefaultTableModel model ;
    ResultSet rset;
    String query;
    Set<String> nameList = new HashSet<>();
    ArrayList barcodeList = new ArrayList();
    Set<String> typeHset = new HashSet<>();
    
    public SearchProduct() {
        initComponents();
        DB.initializeconnection();
        //autoSelcted() ;
        query = "SELECT * FROM foxproject.product" ;
        try 
        {
            rset = DB.stmt.executeQuery(query) ;
            if (!rset.next())
            {
                JOptionPane.showMessageDialog(null,"لا يوجد منتجات");
            }
            else
            {
                do 
                {                    
                    barcodeList.add(rset.getString(1));
                    nameList.add(rset.getString(2));
                    typeHset.add(rset.getString(3));
                    
                } while (rset.next());
                
            }
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(SearchProduct.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        initialSellect() ;
        
    }

    
    private void initialSellect()
    {
        if (searchProCBox.getSelectedIndex()== 0)
         {
             Iterator itr = barcodeList.iterator();
             while (itr.hasNext()) 
             {    
                jComboBox1.addItem(itr.next());
             }
        
         }//end of if
        
        else if (searchProCBox.getSelectedIndex()== 1)
         {
             Iterator itr = nameList.iterator();
             while (itr.hasNext()) 
             {    
                jComboBox1.addItem(itr.next());
             }
        
         }//end of if
        
        else if (searchProCBox.getSelectedIndex()== 2)
         {
             Iterator itr = typeHset.iterator();
             while (itr.hasNext()) 
             {    
                jComboBox1.addItem(itr.next());
             }
        
         }//end of if
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    /*
    private void autoSelcted()
    {
        String query = null ;
        
         if (searchProCBox.getSelectedIndex()== 0)
         {
             query = "SELECT barcode FROM foxproject.product order by barcode ASC" ;
         }
         else if (searchProCBox.getSelectedIndex()== 1)
         {
             query = "Select name from product group by name" ;
         }
         else if (searchProCBox.getSelectedIndex()== 2)
         {
             query = "Select type from product group by type" ;
         }
        
         
         try 
        {
            dbase.rset = DB.stmt.executeQuery(query) ;

            if (!dbase.rset.next())
            {
                JOptionPane.showMessageDialog(null,"no search result, database empty");
            }
            
            else
            {
                
                if (searchProCBox.getSelectedIndex()== 1)
                {
                do
                { 
                    
                    boolean exist = false ;
                    for(int i=0; i<jComboBox1.getItemCount(); i++)
                    {
                        if (jComboBox1.getItemAt(i).toString().equalsIgnoreCase(dbase.rset.getString(1)))
                        {
                            exist = true ;
                            break;
                        }
                        
                    }
                    if (!exist)
                    {
                        jComboBox1.addItem(dbase.rset.getString(1));
                    }
                   
                   
                }
                while(dbase.rset.next());
                 
                }
                
                else
                 {
                    do
                {   
                    jComboBox1.addItem(dbase.rset.getString(1));
                }
                while(dbase.rset.next());
                }
            
            }
        }
        
        catch (SQLException ex) 
        {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error "+ex.getMessage());
        }
         
    }
    
    */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noSearchProBtn = new javax.swing.JButton();
        searchProBtn = new javax.swing.JButton();
        searchProLbl = new javax.swing.JLabel();
        jScrollPanePro = new javax.swing.JScrollPane();
        searchProTbl = new javax.swing.JTable();
        proMainBtn = new javax.swing.JButton();
        searchProCBox = new javax.swing.JComboBox();
        searchProTxt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        noSearchProBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        noSearchProBtn.setText("منتج اخر");
        noSearchProBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noSearchProBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSearchProBtnActionPerformed(evt);
            }
        });

        searchProBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchProBtn.setText("بحث");
        searchProBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchProBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProBtnActionPerformed(evt);
            }
        });

        searchProLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchProLbl.setText("بحث بواسطة:");

        searchProTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الكمية", "سعر البيع", "سعر الجملة", "الباركود", "النوع", "اسم المنتج"
            }
        ));
        searchProTbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPanePro.setViewportView(searchProTbl);

        proMainBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        proMainBtn.setText("القائمة الرئيسية");
        proMainBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proMainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proMainBtnActionPerformed(evt);
            }
        });

        searchProCBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchProCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "الباركود", "اسم المنتج", "نوع المنتج" }));
        searchProCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProCBoxActionPerformed(evt);
            }
        });

        searchProTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProTxtActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePro, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(searchProTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchProCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchProLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(proMainBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(noSearchProBtn)
                .addGap(60, 60, 60)
                .addComponent(searchProBtn)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noSearchProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPanePro, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(proMainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noSearchProBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSearchProBtnActionPerformed
        if(model != null)
        model.setRowCount(0);
        
        searchProTxt.setText(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_noSearchProBtnActionPerformed

    private void searchProBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProBtnActionPerformed
        
        if(!dbase.ValueIsExist(searchProTbl, 3 , searchProTxt.getText()))
        {
        if (searchProCBox.getSelectedIndex()== 0) 
        {
            if(searchProTxt.getText().equals(""))
              {
                 JOptionPane.showMessageDialog(null,"من فضلك ادخل الباركود");
              }
            else
            {
           Object[] row = new Object[6] ;
           query = "Select * from product where barcode = '" + searchProTxt.getText() + "'" ;  
           
        try 
        {
            rset = DB.stmt.executeQuery(query) ;
            if (!rset.next())
            {
                searchProTxt.setText(null) ;
                int dialogResult = JOptionPane.showConfirmDialog(new JPanel(), "المنتج غير موجود .. هل ترغب فى اضافة منتج جديد", "Error", JOptionPane.YES_NO_OPTION);
                if(dialogResult == JOptionPane.YES_OPTION)
                {
                    new add().setVisible(true);
                    this.dispose();
                }
            }
            
            else
            {
                do
                {
                  row[5] = rset.getString(2) ;
                  row[4] = rset.getString(3) ;
                  row[3] = rset.getString(1) ;
                  row[2] = rset.getDouble(5) ;
                  row[1] = rset.getDouble(6) ;
                  row[0] = rset.getLong(4) ;
                
                  model = (DefaultTableModel) searchProTbl.getModel() ;
                  model.addRow(row) ;
                } while(rset.next());
            }
       }
        
        catch (SQLException ex) 
         {
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
         }
        
            }
        
        }
        
        else if (searchProCBox.getSelectedIndex()== 1)
        {
            if(searchProTxt.getText().equals(""))
              {
                 JOptionPane.showMessageDialog(null,"من فضلك ادخل اسم المنتج");
              }
            else
            {
           Object[] row = new Object[6] ;
           query = "Select * from product where name = '" + searchProTxt.getText() + "'" ;  
        
        try 
        {
            rset = DB.stmt.executeQuery(query) ;
            if (!rset.next())
            {
                searchProTxt.setText(null) ;
                int dialogResult = JOptionPane.showConfirmDialog(new JPanel(), "المنتج غير موجود .. هل ترغب فى اضافة منتج جديد", "Error", JOptionPane.YES_NO_OPTION);
                if(dialogResult == JOptionPane.YES_OPTION)
                {
                    new add().setVisible(true);
                    this.dispose();
                }
            }
            
            else
            {
                do
                {
                  row[5] = rset.getString(2) ;
                  row[4] = rset.getString(3) ;
                  row[3] = rset.getString(1) ;
                  row[2] = rset.getDouble(5) ;
                  row[1] = rset.getDouble(6) ;
                  row[0] = rset.getLong(4) ;
                
                  if(!dbase.ValueIsExist(searchProTbl, 3 , row[3].toString()))
                  {
                     model = (DefaultTableModel) searchProTbl.getModel() ;
                     model.addRow(row) ;
                  }
                  
                } while(rset.next());
            }
       }
        
        catch (SQLException ex) 
         {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
         }
        
            }
            
        }
      
        /*
        else if (searchProCBox.getSelectedIndex()== 2)
        {
           String query = "Select * from product where type = '" + searchProTxt.getText() + "'" ;  
            try {
                dbase.rset = dbase.stmt.executeQuery(query) ;
                searchProTbl.setModel(DbUtils.resultSetToTableModel(dbase.rset));
            }
            catch (SQLException ex) {
                Logger.getLogger(SearchProduct.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex.getMessage());
            }
             
            */
        
        else if (searchProCBox.getSelectedIndex()== 2)
       {
           if(searchProTxt.getText().equals(""))
              {
                 JOptionPane.showMessageDialog(null,"من فضلك ادخل نوع المنتج");
              }
           else
           {
           Object[] row = new Object[6] ;
           query = "Select * from product where type = '" + searchProTxt.getText() + "'" ;  
        
        try 
        {
            rset = DB.stmt.executeQuery(query) ;
            if (!rset.next())
            {
                searchProTxt.setText(null) ;
                int dialogResult = JOptionPane.showConfirmDialog(new JPanel(), "المنتج غير موجود .. هل ترغب فى اضافة منتج جديد", "Error", JOptionPane.YES_NO_OPTION);
                if(dialogResult == JOptionPane.YES_OPTION)
                {
                    new add().setVisible(true);
                    this.dispose();
                }
            }
            
            else
            {
                do
                {
                  row[5] = rset.getString(2) ;
                  row[4] = rset.getString(3) ;
                  row[3] = rset.getString(1) ;
                  row[2] = rset.getDouble(5) ;
                  row[1] = rset.getDouble(6) ;
                  row[0] = rset.getLong(4) ;
                  
                  if(!dbase.ValueIsExist(searchProTbl, 3 , row[3].toString()))
                  {
                     model = (DefaultTableModel) searchProTbl.getModel() ;
                     model.addRow(row) ;
                  }
                  
                } while(rset.next());
            }
       }
        
        catch (SQLException ex) 
         {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JPanel(), "خطأ فى الاتصال بقاعدة البيانات.. تأكد من تشغيل السيرفر", "Error", JOptionPane.ERROR_MESSAGE);
         }
        
           }
        
     }
    
   }
        else
        {
            JOptionPane.showMessageDialog(null,"تم البحث بالفعل");
        }
       
    
    }//GEN-LAST:event_searchProBtnActionPerformed

    private void proMainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proMainBtnActionPerformed
        new MainPage().setVisible(true) ;
        this.dispose();
    }//GEN-LAST:event_proMainBtnActionPerformed

    private void searchProCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProCBoxActionPerformed
        searchProTxt.setText(null);
        jComboBox1.removeAllItems();
        initialSellect();
        //autoSelcted() ;        //not used now
    }//GEN-LAST:event_searchProCBoxActionPerformed

    private void searchProTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProTxtActionPerformed
        searchProBtnActionPerformed(evt) ;
    }//GEN-LAST:event_searchProTxtActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem() == null)
            searchProTxt.setText(null);
        else 
            searchProTxt.setText(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SearchProduct().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPanePro;
    private javax.swing.JButton noSearchProBtn;
    private javax.swing.JButton proMainBtn;
    private javax.swing.JButton searchProBtn;
    private javax.swing.JComboBox searchProCBox;
    private javax.swing.JLabel searchProLbl;
    private javax.swing.JTable searchProTbl;
    private javax.swing.JTextField searchProTxt;
    // End of variables declaration//GEN-END:variables
}
